spring:
  application:
    name: microservice1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443
      client:
        registration:
          webapp:
            client-id: webapp
            client-secret: webappSecret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,offline_access,read,write
        provider:
          webapp:
            authorization-uri: http://localhost:8443/oauth2/authorize
            token-uri: http://localhost:8443/oauth2/token
            jwk-set-uri: http://localhost:8443/oauth2/jwks
            issuer-uri: http://localhost:8443
